image: docker

build_image:
  script:
    - docker info
    - docker build -t "$IMAGE_NAME:latest"
    - docker tag "$IMAGE_NAME:latest" "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"

push_image:
  only:
    - master
  script:
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push "$IMAGE_NAME:latest"
    - docker push "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
