#!/usr/bin/env bash

set -e

TEMP=$(mktemp -d)

cd "$TEMP"

GET="Linux-64bit.tar.gz"
BASE="https://api.github.com/repos/gohugoio/hugo/releases/latest"
DL=$(curl -s $BASE | jq -r ".assets[] | select(.name | test(\"${GET}\")) | .browser_download_url")

curl -L $DL | tar xvzf -
mv hugo /usr/local/bin

cd /
rm -rf "$TEMP"

