#!/usr/bin/env bash

set -xe

TEMP=$(mktemp -d)

cd "$TEMP"

export GET="Linux-64bit.tar.gz"
export BASE="https://api.github.com/repos/gohugoio/hugo/releases/latest"
DL=$(curl -s $BASE | jq -r ".assets[] | select(.name | test(\"${GET}\")) | .browser_download_url")

curl -L $DL | tar xvzf -
mv hugo /usr/local/bin

cd /
rm -rf "$TEMP"

